[[mousetrap_apple]]
arch = "x86_64"
git-tree-sha1 = "358a5403bd05700e33b3a388a0cd064fca7e7386"
os = "macos"

    [[mousetrap_apple.download]]
    sha256 = "fb98a816c9afe09748832981366640bf085ceba587a4bf7b20c0af42038d876d"
    url = "https://github.com/Clemapfel/mousetrap_apple_jll/releases/download/mousetrap_apple-v0.1.0+0/mousetrap_apple.v0.1.0.x86_64-apple-darwin.tar.gz"
