[[mousetrap_apple]]
arch = "aarch64"
git-tree-sha1 = "a8a629235c91dd5387ac3c9af394b662656b603e"
os = "macos"

    [[mousetrap_apple.download]]
    sha256 = "88d0ad30244713777e1e88a74020395bc88031ce6ff651c054398a783984dccf"
    url = "https://github.com/Clemapfel/mousetrap_apple_jll/releases/download/mousetrap_apple-v0.2.1+0/mousetrap_apple.v0.2.1.aarch64-apple-darwin.tar.gz"
[[mousetrap_apple]]
arch = "x86_64"
git-tree-sha1 = "e69a7299e9a31aaa5e96c5bc161c960dbeb6562f"
os = "macos"

    [[mousetrap_apple.download]]
    sha256 = "f279b25cb4e778be3739a129686728e2744e8c68a87d094580c84fb5890cf073"
    url = "https://github.com/Clemapfel/mousetrap_apple_jll/releases/download/mousetrap_apple-v0.2.1+0/mousetrap_apple.v0.2.1.x86_64-apple-darwin.tar.gz"
